### ISSUE TITLE
Restructure Bottle View

### ISSUE THREAD

**Issue by jannuary** [bottlesdevs/ui-study#1]
### The Why
Recently, the bottle view has grown in complexity - it now sports a sidebar and 20% more unlabeled buttons. Furthermore, the hierarchy is all over the place - the supposedly 'main' view, along with shortcuts for programs (which is about the most important thing) lists a bunch of options for Wine and a weird pseudo-toolbar with different button styles, while not necessarily pointing towards, say, dependencies or settings - they're just another tab in the sidebar pile.

### The What
We're gonna kill the sidebar, kill the 'Dashboard' and have a simplified main view with a header and three PreferenceGroups - one for installed programs, other with links to preferences, dependencies and versions; and the third will have links towards help materials. Wine things, as well as bottle management things (delete, rename, reboot) will go in the three-dot menu.

As such, the settings/backups/depends are not an entry in the sidebar, but a leaflet page, which should improve the navigation somewhat. 

Tentative mockup herein:
<img width="892" alt="Slice 1" src="https://user-images.githubusercontent.com/27908024/152187746-6aaec66e-eec1-4e3b-b4c1-13f3cf5e9ce5.png">

cc @alvarlagerlof @mirkobrombin

**Comment by jannuary** [comment]
> One thing I wonder is how you would start a program in this and also what the right arrow for programs beings you to.

Yeah, the icon would probably be a box with an arrow instead, though i wonder if we should still keep the play toggle button

> Would preferences and snapshots open up a new "window layer" like the bottle view of would they be popups?

It would be a "layer" - as in a HdyLeafletPage
![Kooha-02-02-2022-23-00-47](https://user-images.githubusercontent.com/27908024/152190318-3a808b95-7e04-40ce-b670-45373e2602ba.gif)

**Comment by mirkobrombin** [comment]
I've moved this issue to a new repository, where we can place any concepts and more related stuff.

**Comment by jannuary** [comment]
Mockup update: 
![bottels](https://user-images.githubusercontent.com/27908024/166192516-8f28963c-c7ab-4ec6-9ac6-2757192a2899.png)

**Comment by alvarlagerlof** [comment]
@jannuary Is the settings button next to the blue button at the top for this still, or does it open preferences? 
![image](https://user-images.githubusercontent.com/14835120/168321826-35c8b61e-fbfe-43da-9e1d-69a529e58760.png)

Also, I am curious what would happen when you click "Add shortcuts"?

**Comment by jannuary** [comment]
> @jannuary Is the settings button next to the blue button at the top for this still, or does it open preferences? 
> ![image](https://user-images.githubusercontent.com/14835120/168321826-35c8b61e-fbfe-43da-9e1d-69a529e58760.png)
> 
> Also, I am curious what would happen when you click "Add shortcuts"?
> 

Yeah, brings up the same popover. "Add Shortcut..." would bring up a file manager where you can choose an exe.

**Comment by mirkobrombin** [comment]
First of all, congratulations, it is a really good job. 

Does this widget exists?
![image](https://user-images.githubusercontent.com/9479903/168338165-e3b76bd9-27c5-400a-b870-228ffbb2db01.png)

**Comment by mirkobrombin** [comment]
Another question: the programs list will grow making other options hard to reach. Have you already thought of something to manage the problem?

**Comment by alvarlagerlof** [comment]
> Yeah, brings up the same popover. "Add Shortcut..." would bring up a file manager where you can choose an exe.

Sounds great.

**Comment by jannuary** [comment]
> First of all, congratulations, it is a really good job. 
> 
> Does this widget exists?

I think so, though it would probably be replaced with a simple + in the list header.

> Another question: the programs list will grow making other options hard to reach. Have you already thought of something to manage the problem?

Cap the list and have an another page for the rest of the programs.

**Comment by mirkobrombin** [comment]
I found a simple solution to sort that list by usage . It would also be great to allow the user pinning programs
